"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var menuRouter = [];
exports.menuRouter = menuRouter;
var otherRouter = [];
exports.otherRouter = otherRouter;
var errRouter = [];
exports.errRouter = errRouter;
var appConfig;
exports.appConfig = appConfig;
